### ISSUE TITLE
Add profiling

### ISSUE THREAD

**Issue by djavorszky** [javorszky/go-generate-salts#3]

**Comment by djavorszky** [comment]
Pushed.

You can check the following information:
goroutine
heap
threadcreate
block
mutex

go tool localhost:8090/debug/pprof/$oneoftheabove

need to call go get -u as using package.

**Comment by javorszky** [comment]
```
$ go tool localhost:8090/debug/pprof/block
go tool: bad tool name "localhost:8090/debug/pprof/block"
```

Questions:
1. does the app need to run already?
2. do I need to be in the same folder?

**Comment by javorszky** [comment]
Closed with https://github.com/javorszky/go-generate-salts/commit/7e97628df678be0c571db5c1a59e6f9c1390db3b
